# El servicio de bases de datos
services:
  postgres: # Nombre del servicio
    image: postgres:15
    container_name: demo_postgres
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"

# El servicio de administrador de bases de datos pgAdmin
# Service for pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: demo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"